name: Deploy to GitHub Pages

on:
  [push]

jobs:
  dotnetformat:
    name: DotNet Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet-format
        run: dotnet format client/StackNServe.csproj --verify-no-changes
    

  SonarCloud :
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Set up Python for server-side tests and analysis
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/server.Tests/requirements.txt
          pip install coverage pytest-cov

      # Run Python tests and generate coverage report
      - name: Run Python tests and generate coverage report
        run: |
          coverage run --source=server -m pytest tests/server.Tests
          coverage xml -o coverage.xml

      # Set up .NET SDK for client-side tests and analysis
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
    
      # Cache SonarCloud packages
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Cache SonarCloud scanner
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      
      # Install SonarCloud scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p .sonar/scanner
          dotnet tool update dotnet-sonarscanner --tool-path .sonar/scanner

      # Install dotCover for code coverage on .NET
      - name: Install dotCover
        run: dotnet tool install --global JetBrains.dotCover.GlobalTool

      - name: Update dotcover
        run: dotnet tool update --global JetBrains.dotCover.GlobalTool

      # SonarCloud analysis begins
      - name: Begin SonarCloud Analysis
        run: ./.sonar/scanner/dotnet-sonarscanner begin /k:"CS455-Assignment-1_StackNServe" /o:"cs455-assignment-1" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths="dotCover.Output.html" /d:sonar.python.version=3.9 /d:sonar.python.coverage.reportPaths=coverage.xml /d:sonar.exclusions="**/dotCover.Output/**,dotCover.Output.html,**/Report/**"

      # Build the solution after starting SonarCloud analysis
      - name: Build the solution
        run: dotnet build client/StackNServe.csproj --configuration Debug

      # Build the test project explicitly to generate test DLLs
      - name: Build the test project
        run: dotnet build tests/client.Tests/ --configuration Debug

      # Run tests and collect coverage
      - name: Run tests and collect coverage
        run: |
          dotnet dotcover test tests/client.Tests/StackNServe.Tests.csproj --dcReportType=HTML --output=dotcover-report.html --dcFilters=-:module=Bunit.Core > test-results.txt
          cat test-results.txt

      # Upload unit test results and coverage reports as artifacts
      - name: Upload Unit Test and Coverage Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt           

      # Finalize the SonarCloud analysis after building the project
      - name: End SonarCloud Analysis
        run: ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      # Fetch detailed SonarCloud results and output in the logs
      - name: Fetch and display detailed SonarCloud analysis results
        if: always()
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Fetching detailed analysis results..."
          curl -u $SONAR_TOKEN: "https://sonarcloud.io/api/issues/search?componentKeys=CS455-Assignment-1_StackNServe" > sonarcloud-results.json
          echo "Analysis results:"
          cat sonarcloud-results.json | jq '.issues[] | {key, component, severity, message, line}' 
      # Upload the SonarCloud results JSON as an artifact
      - name: Upload SonarCloud results artifact
        if: always()  
        uses: actions/upload-artifact@v3
        with:
          name: sonarcloud-results
          path: sonarcloud-results.json 
      - name: Check SonarCloud Quality Gate
        id: quality-gate
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          SONAR_STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=CS455-Assignment-1_StackNServe" | jq -r '.projectStatus.status')
          if [ "$SONAR_STATUS" != "OK" ]; then
            echo "Quality gate failed: $SONAR_STATUS"
            exit 1
          else
            echo "Quality gate passed!"
          fi

  deploy-to-github-pages:
    needs: [SonarCloud, dotnetformat]
    runs-on: ubuntu-latest
    if: success()
    steps:
    # Checkout the code from the master branch
    - uses: actions/checkout@v3
    
    # Setup .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.107

    # Publish the project
    - name: Publish .NET Core Project
      run: dotnet publish client/StackNServe.csproj -c Release -o release --nologo
    
    # Verify that index.html exists after the publish
    - name: Verify index.html exists
      run: |
        if [ ! -f release/wwwroot/index.html ]; then
          echo "Error: index.html not found!"
          exit 1
        fi

    # Change base tag in index.html to point to the correct subdirectory (StackNServe)
    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/StackNServe\/" \/>/g' release/wwwroot/index.html
    
    # Copy index.html to 404.html for GitHub Pages fallback routing
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Add a .nojekyll file to prevent Jekyll processing
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # Deploy the wwwroot folder to the gh-pages branch
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot