name: Deploy to GitHub Pages

on:
  [push]

jobs:
  dotnetformat:
    name: DotNet Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet-format
        run: dotnet format client/StackNServe.csproj --verify-no-changes
    

  SonarCloud :
    name: SonarCloud
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/server.Tests/requirements.txt
      
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      
      - name: Install dotCover
        run: dotnet tool install --global JetBrains.dotCover.GlobalTool

      - name: Begin SonarCloud Analysis
        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"CS455-Assignment-1_StackNServe" /o:"cs455-assignment-1" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html /d:sonar.python.coverage.reportPaths=server-coverage.xml /d:sonar.sources="client,server" /d:sonar.tests="tests" /d:sonar.exclusions="**/bin/**,**/obj/**,**/dotCover.Output/**,dotCover.Output.html,**/client/src/**,client/wwwroot/appsettings.json" /d:sonar.test.exclusions="**/tests/**"

      - name: Build the solution
        run: dotnet build client/StackNServe.csproj --configuration Debug

      - name: Build the test project
        run: dotnet build tests/client.Tests/ --configuration Debug

      - name: Run tests and collect coverage
        run: |
          dotnet dotcover test tests/client.Tests/StackNServe.Tests.csproj --dcReportType=HTML > test-results.txt
          cat test-results.txt

      - name: Run Python server tests and collect coverage
        run: |
            pytest tests/server.Tests --cov=server --cov-report xml:server-coverage.xml
      
      - name: Upload Unit Test and Coverage Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt     

      - name: Upload Server Coverage
        uses: actions/upload-artifact@v3
        with:
          name: server-coverage-results
          path: coverage.xml           

      - name: End SonarCloud Analysis
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Fetch and display detailed SonarCloud analysis results
        if: always()
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Fetching detailed analysis results..."
          curl -u $SONAR_TOKEN: "https://sonarcloud.io/api/issues/search?componentKeys=CS455-Assignment-1_StackNServe" > sonarcloud-results.json
          echo "Analysis results:"
          cat sonarcloud-results.json | jq '.issues[] | {key, component, severity, message, line}' 
      - name: Upload SonarCloud results artifact
        if: always()  
        uses: actions/upload-artifact@v3
        with:
          name: sonarcloud-results
          path: sonarcloud-results.json 
      - name: Check SonarCloud Quality Gate
        id: quality-gate
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          SONAR_STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=CS455-Assignment-1_StackNServe" | jq -r '.projectStatus.status')
          if [ "$SONAR_STATUS" != "OK" ]; then
            echo "Quality gate failed: $SONAR_STATUS"
            exit 1
          else
            echo "Quality gate passed!"
          fi

  deploy-to-github-pages:
    needs: [SonarCloud, dotnetformat]
    runs-on: ubuntu-latest
    if: success()
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.107

    - name: Publish .NET Core Project
      run: dotnet publish client/StackNServe.csproj -c Release -o release --nologo
    
    - name: Verify index.html exists
      run: |
        if [ ! -f release/wwwroot/index.html ]; then
          echo "Error: index.html not found!"
          exit 1
        fi

    - name: Change base-tag in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/StackNServe\/" \/>/g' release/wwwroot/index.html
    
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
