name: Nightly Performance Test

on:
  schedule:
    # Runs at midnight (IST) every day
    - cron: '30 18 * * *'
  workflow_dispatch: 

jobs:
  nightly_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install locust selenium

      - name: Install ChromeDriver and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin
          sudo apt-get install -y google-chrome-stable
        
          # Verify installations
          google-chrome --version
          chromedriver --version

      - name: Test Server Accessibility
        run: |
          curl -I https://stacknserve.onrender.com  

      - name: Run Locust performance test 1
        run: |
          locust -f "performance tests/server/leaderboard.Tests.py" --headless -u 100 -r 10 -t 1m --html=leaderboard_report.html || true

      - name: Run Locust performance test 2
        run: |
          locust -f "performance tests/server/home.Tests.py" --headless -u 100 -r 10 -t 1m --html=home_report.html || true

      - name: Run Selenium test 1
        run: |
          python "performance tests/client/Home.Tests.py" > selenium_home_output.txt || true

      - name: Run Selenium test 2
        run: |
          python "performance tests/client/Leaderboard.Tests.py" > selenium_leaderboard_output.txt || true

      - name: Run Selenium test 3
        run: |
          python "performance tests/client/Player_Guide.Tests.py" > selenium_playerguide_output.txt || true

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: nightly-test-reports
          path: |
            leaderboard_report.html
            home_report.html
            selenium_home_output.txt
            selenium_leaderboard_output.txt
            selenium_playerguide_output.txt
